version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    command: bash -c "npm install && npm run start"
    extra_hosts:
    - "host.docker.internal:172.17.0.1"

  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data_challenge:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nestjs

volumes:
  mongodb_data_challenge:
    driver: local
